In [2]:
import os
import glob
import pandas as pd

path = './'
os.chdir(path)
all_csv_files = glob.glob('*.csv')

database = []

for file in all_csv_files:
    df = pd.read_csv(path + file)[::-1]
    database.append(df)

In [8]:
data = pd.concat(database, ignore_index=True)
data = data.iloc[:, :-1]
data.to_csv("database.csv")

In [7]:
data.iloc[:, :-1]

,Symbol,Date,Open,High,Low,Close,Percent Change,Volume
0,SDLBSL,2020-08-06,390.0,397.0,390.0,397.0,1.79,20.0
1,SDLBSL,2020-08-09,404.0,436.0,404.0,436.0,9.82,60.0
2,SDLBSL,2020-08-10,444.0,479.0,444.0,479.0,9.86,100.0
3,SDLBSL,2020-08-11,488.0,526.0,488.0,526.0,9.81,100.0
4,SDLBSL,2020-08-12,536.0,578.0,536.0,578.0,9.89,140.0
...,...,...,...,...,...,...,...,...
593057,MSLB,2021-11-14,1920.0,1931.0,1895.0,1931.0,-0.97,820.0
593058,MSLB,2021-11-15,1950.0,1989.0,1900.0,1910.0,-1.09,1160.0
593059,MSLB,2021-11-16,1910.0,2031.8,1900.0,2031.8,6.38,849.0
593060,MSLB,2021-11-17,2072.4,2072.4,1991.0,2009.9,-1.08,1104.0
593061,MSLB,2021-11-18,2009.9,2009.9,1937.0,1950.0,-2.98,682.0

In [12]:
data.loc[data["Symbol"] == "MFIL"].set_index("Date")

           Symbol   Open   High    Low  Close Percent Change  Volume
Date
2012-11-08   MFIL    0.0  150.0  150.0  150.0           0.00    50.0
2012-11-20   MFIL  150.0  153.0  153.0  153.0           2.00    50.0
2012-11-26   MFIL  153.0  156.0  156.0  156.0           1.96   900.0
2013-01-20   MFIL  156.0  149.0  147.0  147.0          -5.77    20.0
2013-01-21   MFIL  147.0  140.0  136.0  136.0          -7.48    30.0
...           ...    ...    ...    ...    ...            ...     ...
2013-01-21   MFIL  147.0  140.0  136.0  136.0          -7.48    30.0
2013-01-20   MFIL  156.0  149.0  147.0  147.0          -5.77    20.0
2012-11-26   MFIL  153.0  156.0  156.0  156.0           1.96   900.0
2012-11-20   MFIL  150.0  153.0  153.0  153.0           2.00    50.0
2012-11-08   MFIL    0.0  150.0  150.0  150.0           0.00    50.0

[2509 rows x 7 columns]